# fly.toml app configuration file generated for featureset on 2023-08-05T14:28:54-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "featureset"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  cmd = ["start.sh"]
  entrypoint = ["sh"]
  auto_rollback = true

[build]

[deploy]
  strategy = "rolling"

[[mounts]]
  source = "data"
  destination = "/data"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "1m30s"
    timeout = "2s"
    grace_period = "3s"

  [[services.http_checks]]
    interval = "5m0s"
    timeout = "5s"
    grace_period = "5s"
    method = "get"
    path = "/api/healthcheck"
    protocol = "http"
    tls_skip_verify = false
