name: ðŸš€ Deploy
on:
  push:
    branches:
      - main
      - dev
  pull_request: {}

permissions:
  actions: write
  contents: read

jobs:
  lint:
    name: â¬£ ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Run Lint
        run: npm run lint

  typecheck:
    name: Ê¦ TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Run Typechecking
        run: npm run typecheck --if-present

  playwright:
    name: ðŸŽ­ Playwright
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Copy Environment Variables
        run: cp .env.example .env

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Setup Database
        run: npx prisma migrate reset --force --skip-seed

      - name: Build
        run: npm run build

      - name: Run Playwright Tests
        run: npx playwright test

      - name: Upload Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  deploy:
    name: ðŸš€ Deploy
    runs-on: ubuntu-latest
    needs: [lint, typecheck, playwright, build]
    # Only build / deploy main branch on pushes.
    if: ${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') && github.event_name == 'push' }}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Read App Name
        uses: SebRollen/toml-action@v1.0.2
        id: app_name
        with:
          file: 'fly.toml'
          field: 'app'

      - name: Deploy Staging
        if: ${{ github.ref == 'refs/heads/dev' }}
        uses: superfly/flyctl-actions@1.3
        with:
          args:
            'deploy --remote-only --build-arg COMMIT_SHA=${{ github.sha }} --env APP_VERSION=${{ github.sha }}  --app ${{
                steps.app_name.outputs.value }}-staging'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy Production
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: superfly/flyctl-actions@1.3
        with:
          args: 'deploy --remote-only --build-arg COMMIT_SHA=${{ github.sha }} --env APP_VERSION=${{ github.sha }}  --app ${{
                steps.app_name.outputs.value }}'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
